#!/bin/bash

set +x

export test_output_file="test-output.xml"
export lint_output_file="lint-output.xml"

(npm run testem-ci)
test_status=$?
(npm run lint-ci)
lint_status=$?

mkdir -p $CIRCLE_TEST_REPORTS/xunit

mv $test_output_file $CIRCLE_TEST_REPORTS/xunit/
mv $lint_output_file $CIRCLE_TEST_REPORTS/xunit/

unset test_output_file
unset lint_output_file

exit $((test_status + lint_status))
