#!/bin/bash

set +x

mkdir -p $CIRCLE_TEST_REPORTS/xunit

export test_output_file="${CIRCLE_TEST_REPORTS}/xunit/test-output.xml"
export lint_output_file="${CIRCLE_TEST_REPORTS}/xunit/lint-output.xml"

npm run lint-ci && npm run testem-ci
