# Site settings
title: Shopify Buy Button JS
email: buybutton@shopify.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/buy-button-js"
url: "https://shopify.github.io"
sass:
  cache: true

# Build settings
markdown: kramdown
